services:
  postgres:
    image: postgres:16
    container_name: memorias_auth_db
    environment:
      POSTGRES_DB: memorias_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - memorias_auth_data:/var/lib/postgresql/data

volumes:
  memorias_auth_data:
